### ISSUE TITLE
能不能实现注册多种序列化方式，resolve时，根据名称什么的进行注入？

### ISSUE THREAD

**Issue by heyuquan** [dotnetcore/AspectCore-Framework#113]
https://www.cnblogs.com/lori/p/5942025.html
像 autofac 中的
builder.RegisterType<Mul1>()
       .Named<IMul>("Mul1")
       .InstancePerDependency();
container.ResolveNamed<IMul>("Mul1");

**Comment by liuhaoyang** [comment]
在保证性能的前提下，你可以帮忙贡献一下吗？

**Comment by heyuquan** [comment]
@liuhaoyang  非常感谢邀请。   能力有限，其实本身是非常想加入开源社区的。   后续有能力了，再加入

**Comment by heyuquan** [comment]
@liuhaoyang 还有一个问题，IOC 时，能不能限定某个类下面DI的是某个实现？   比如A，B 都有一个IRepository 的仓储属性，现在想让A自动DI mongodb实现，B自动DI mysql的实现？

可能这个和上一个问题是相同的，  所以希望作者如果后续考虑加入，一起进行实现

**Comment by liuhaoyang** [comment]
暂时不考试实现
