### ISSUE TITLE
升级到0.4版本，Assert.Throws<AspectInvocationException>( action )报错中断VS

### ISSUE THREAD

**Issue by UtilCore** [dotnetcore/AspectCore-Framework#114]
1. 描述：
util升级aspectcore到4.0版本，运行单元测试发现有错，断点调试到达Assert.Throws<AspectInvocationException>( action )语句时，catch无法捕获，直接中断VS。
2. 重现：
可下载util（https://github.com/dotnetcore/util），将util类库的aspectcore升级到0.4版本，运行Util.Tests单元测试项目，就能看见。
3. 代码：
`
        /// <summary>
        /// 测试添加时验证无效
        /// </summary>
        [Fact]
        public void TestAdd_Invalid() {
            EntitySample entity = new EntitySample();
            var repository = _container.Create<IRepositorySample>();
            AssertHelper.Throws<Warning> ( () => repository.Add( entity ), "名称不能为空" );
        }`
`
     /// <summary>
    /// 实体样例
    /// </summary>
    [DisplayName( "实体样例" )]
    public class EntitySample : AggregateRoot<EntitySample> {
        public EntitySample( ) : this( Guid.NewGuid() ) {
        }

        public EntitySample( Guid id ) : base( id ) {
        }

        /// <summary>
        /// 名称
        /// </summary>
        [Required(ErrorMessage = "名称不能为空")]
        public string Name { get; set; }

        /// <summary>
        /// 忽略值
        /// </summary>
        [IgnoreMap]
        public string IgnoreValue { get; set; }
    }
`
`
     /// <summary>
    /// 断言操作
    /// </summary>
    public class AssertHelper {
        /// <summary>
        /// 抛出异常，并从异常消息中搜索特定关键字
        /// </summary>
        /// <typeparam name="TException">异常类型</typeparam>
        /// <param name="action">操作</param>
        /// <param name="keyword">关键字</param>
        public static TException Throws<TException>( Action action,string keyword = "" ) where TException : Exception {
            var exception = GetException<TException>( action );
            if( !string.IsNullOrWhiteSpace( keyword ) )
                Assert.Contains( keyword, exception.Message );
            return exception;
        }

        /// <summary>
        /// 获取异常
        /// </summary>
        private static TException GetException<TException>( Action action ) where TException : Exception {
            try {
                var exception = Assert.Throws<AspectInvocationException>( action );
                return (TException)exception.InnerException;
            }
            catch {
                return Assert.Throws<TException>( action );
            }
        }
}
`

**Comment by huoshan12345** [comment]
排查了一下，是因为AspectActivator的27行：
```
if (task.IsFaulted)
        throw context.InvocationException(task.Exception);
```
这里抛出了一个AggregateException，实际上应该AggregateException的内部异常
