### ISSUE TITLE
配合 autofac，全局拦截器不起作用

### ISSUE THREAD

**Issue by yun738243875** [dotnetcore/AspectCore-Framework#115]
.net core  web 
方法签名
public IServiceProvider ConfigureServices(IServiceCollection services)

--1
services.AddDynamicProxy(option =>
{
	option.Interceptors.AddTyped< GlobalInterceptor >();
});

--2
//autofac
ContainerBuilder builder = new ContainerBuilder();
builder.Populate(services);
builder.RegisterDynamicProxy();
this.ApplicationContainer = builder.Build();
return new AutofacServiceProvider(this.ApplicationContainer);

**Comment by Shinetaku** [comment]
同问题，请问如何解决的。BuildAspectCoreServiceProvider、AutofacServiceProvider这两个类只能二选一么。那同时用autofac和拦截器就不可能了？

**Comment by Shinetaku** [comment]
![image](https://user-images.githubusercontent.com/17084061/45370391-bfea2c00-b61a-11e8-906b-6c4703cefdc0.png)
![image](https://user-images.githubusercontent.com/17084061/45370415-cbd5ee00-b61a-11e8-8d38-10de99f1d4a8.png)
记录一下解决办法。

**Comment by ww198643** [comment]
我也遇到同样的问题，最终怎么解决的？上面的截图没看明白

**Comment by Shinetaku** [comment]
使用Autofac的ServiceProvider,不用AspectCoreServiceProvider，同时使用Aspect的Autofac扩展，注册动态代理到容器里。上面是两张图，分开看。
