### ISSUE TITLE
在.NET 4.5.1平台下，使用AspectCore Aop和Polly出现错误

### ISSUE THREAD

**Issue by yuchen1030** [dotnetcore/AspectCore-Framework#125]
在.NET 4.5.1 平台MVC框架下，使用AspectCore Aop和Polly实现异常处理（HystrixCommandAttribute特性），但下列三个测试方法，
（1）在MaxRetryTimes = 0时，偶尔测试通过，但更多的是直接报错；
（2）在MaxRetryTimes > 0时，直接不给反应啊；

方法1：http://localhost:1319/Home/HelloAsync
方法2：http://localhost:1319/Home/GetTest
方法3：http://localhost:1319/Home/Test  。

相关代码（AspectCore 版本 0.2.2.0）：
1、   polly异常处理拦截器（poll版本6.0.0.0）
    [AttributeUsage(AttributeTargets.Method)]
    public class HystrixCommandAttribute : AbstractInterceptorAttribute
    {
        public HystrixCommandAttribute(string fallBackMethod)
        {
            FallBackMethod = fallBackMethod;
        }

        //public HystrixCommandAttribute(string fallBackMethod, int maxRetryTimes)
        //{
        //    FallBackMethod = fallBackMethod;
        //    MaxRetryTimes = maxRetryTimes;
        //}

        // 最多重试次数（0表示不重试）
        public int MaxRetryTimes { get; set; } = 0;

        // 重试间隔（毫秒）
        public int RetryIntervalMilliseconds { get; set; } = 1000;

        // 是否启用熔断
        public bool EnableCircuitBreaker { get; set; } = true;

        // 允许异常的次数
        public int ExceptionsAllowedBeforeBreaking { get; set; } = 3;

        // 熔断时长（毫秒）
        public int MillisecondsOfBreak { get; set; } = 10000;

        // 超时时长（毫秒，0表示不检测超时）
        public int TimeOutMilliseconds { get; set; } = 5000;

        // 缓存时长（毫秒）
        public int CacheTTLMilliseconds { get; set; } = 20000;

        // 熔断后执行的方法名称
        public string FallBackMethod { get; set; }

        private static readonly IMemoryCache memoryCache = new MemoryCache(new MemoryCacheOptions());

        public override async Task Invoke(AspectContext context, AspectDelegate next)
        {
            IAsyncPolicy policy = Policy
                .Handle<Exception>()
                .FallbackAsync((t) =>
                {
                    var fallBackMethod = context.ServiceMethod.DeclaringType.GetMethod(FallBackMethod);
                    var fallBackResult = fallBackMethod.Invoke(context.Implementation, context.Parameters);
                    context.ReturnValue = fallBackResult;
                    return Task.FromResult(0);
                });

            if (MaxRetryTimes > 0)
            {
                var warPolicy = Policy
                    .Handle<Exception>()
                    .WaitAndRetryAsync(MaxRetryTimes,
                                  i => TimeSpan.FromMilliseconds(RetryIntervalMilliseconds));
                //policy = policy.Wrap(warPolicy);
                policy = Policy.WrapAsync(policy, warPolicy);
            }

            if (EnableCircuitBreaker)
            {
                var cbPolicy = Policy
                    .Handle<Exception>()
                    .CircuitBreakerAsync(ExceptionsAllowedBeforeBreaking,
                                    TimeSpan.FromMilliseconds(MillisecondsOfBreak));
                //policy = policy.Wrap(cbPolicy);
                policy = Policy.WrapAsync(policy, cbPolicy);
            }

            if (TimeOutMilliseconds > 0)
            {
                var tPolicy = Policy.TimeoutAsync(() => TimeSpan.FromMilliseconds(TimeOutMilliseconds), TimeoutStrategy.Pessimistic);
                //policy = policy.Wrap(tPolicy);
                policy = Policy.WrapAsync(policy, tPolicy);
            }

            if (CacheTTLMilliseconds > 0)
            {
                //用类名+方法名+参数的下划线连接起来作为缓存key
                string cacheKey = "HystrixMethodCacheManager_key_"
                    + context.ServiceMethod.DeclaringType + "."
                    + context.ServiceMethod + string.Join("_", context.Parameters);

                object cacheValue = null;
                // 尝试到缓存中获取
                if (memoryCache.TryGetValue(cacheKey, out cacheValue))
                {
                    context.ReturnValue = cacheValue;
                    //await Task.FromResult(0);
                    await next(context);//执行被拦截的方法;
                }
                else
                {
                    using (var cacheEntry = memoryCache.CreateEntry(cacheKey))
                    {
                        cacheEntry.Value = context.ReturnValue;
                        cacheEntry.AbsoluteExpiration = DateTime.Now + TimeSpan.FromMilliseconds(CacheTTLMilliseconds);
                    }
                    context.ReturnValue = cacheValue;

                    await policy.ExecuteAsync(() => next(context));
                }
            }
            else// 未启用缓存
            {
                //await policy.Execute(() => next(context));
                await (policy as Policy).ExecuteAsync(() => next(context));
            }
        }
    }
2、Person类代码
    public class Person//需要public类
    {
        //[ZZTestAttribute]
        [HystrixCommand(nameof(HelloFallBackAsync) /*, MaxRetryTimes = 1*/)]
        public virtual async Task<string> HelloAsync(string name)//需要是虚方法
        {
            Console.WriteLine("hello" + name);
            String s = null;
            s.ToString();
            return "ok";
        }
        public async Task<string> HelloFallBackAsync(string name)
        {
            Console.WriteLine("执行失败" + name);
            return "fail";
        }

        [HystrixCommand(nameof(AddFall))]
        public virtual int Add(int i, int j)
        {
            String s = null;
            s.ToString();
            return i + j;
        }
        public int AddFall(int i, int j)
        {
            return -1000 - (i + j);
        }
    }
3、注册代码
        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);

            var builder = new ContainerBuilder();

            builder.RegisterType<Person>().As<Person>().InstancePerDependency();

            //注册Mvc Controller的动态代理
            builder.RegisterControllers(typeof(MvcApplication).Assembly);

            //注册AspectCore
            builder.RegisterDynamicProxy(config =>
            {
                RegisterServices(typeof(HystrixCommandAttribute), this.GetType().BaseType.Assembly, config);

            });
            var container = builder.Build();
            DependencyResolver.SetResolver(new AutofacDependencyResolver(container));

        }

        private static void RegisterServices(Type attrType, Assembly asm, IAspectConfiguration config)
        {
            foreach (Type type in asm.GetExportedTypes())
            {
                var methods = type.GetMethods().Where(a => a.GetCustomAttribute(attrType) != null);
                foreach (var item in methods)
                {
                    var curAttr = item.GetCustomAttributesData().Where(a => a.AttributeType == attrType).FirstOrDefault();
                    var args = curAttr.ConstructorArguments.ToList();
                    var args2 = curAttr.NamedArguments.Select(a => a.MemberName).ToList();

                    AspectPredicate[] aspectPredicates = { Predicates.ForService("*Controller"), /*Predicates.ForService("Person")*/ };

                    //  AspectPredicate aspectPredicate2 = Predicates.("*Controller");
                    if (args.Count > 0)
                    {
                        var parasList = args.Select(a => a.Value).ToList();
                        parasList.AddRange(args2);
                        object[] paras = parasList.ToArray();//paras = { "HelloFallBackAsync" };      

                        config.Interceptors.AddTyped<HystrixCommandAttribute>(paras, aspectPredicates);
                    }
                    else
                    {
                        config.Interceptors.AddTyped<HystrixCommandAttribute>(aspectPredicates);
                    }
                }
            }
        }
4、控制器代码：
        public virtual async Task<string> Test()
        {
            var n = await p.HelloAsync("333");
            return n;
        }

        public string GetTest()
        {
            int n = p.Add(1, 1);
            return "value" + n;
        }

        [HttpGet]
        [HystrixCommand(nameof(HelloFallBackAsync) /*, MaxRetryTimes = 1*/)]
        public virtual string HelloAsync()//需要是虚方法
        {
            string name = "123";
            Console.WriteLine("hello" + name);
            String s = null;
            s.ToString();
            return "ok";
        }
        public virtual string HelloFallBackAsync()
        {
            string name = "123";
            Console.WriteLine("执行失败" + name);
            return "fail";
        }

**Comment by liuhaoyang** [comment]
使用AspectCore 1.0+版本呢

**Comment by liuhaoyang** [comment]
已经不支持.NET 4.5.1平台，请使用.NET 4.6.1及以上 或者 .net standard2.x
