### ISSUE TITLE
几个bug和建议需要修复

### ISSUE THREAD

**Issue by SarcoZ** [dotnetcore/AspectCore-Framework#131]
1.  AspectCore.Extensions.Autofac 的例子AspectCore.Extensions.Autofac.Sample全局代理不起作用
2.  使用特性代理，不起作用，使用接口代理(有效)
3.  使用类代理无效
public class TaskService   //: ITaskService //: ITaskService
    {
        [LogInterceptor]
        public bool Run()
        {
            return true;
        }
    }
如上，注册的时候var serviceContaniner = new ServiceContainer();
            serviceContaniner.AddType<TaskService, TaskService>();
            var containerBuilder = new ContainerBuilder();
            //调用Populate扩展方法在Autofac中注册已经注册到ServiceContainer中的服务（如果有）。注：此方法调用应在RegisterDynamicProxy之前
            containerBuilder.Populate(serviceContaniner);
            var configuration = serviceContaniner.Configuration;
最后不起作用
4.使用类代理的时候，如果类没有实现任何接口，那么  var services = e.Component.Services.Select(x => ((IServiceWithType)x).ServiceType).ToList();
            if (!services.All(x => x.GetTypeInfo().CanInherited()) || services.All(x => x.GetTypeInfo().IsNonAspect()))
            {
                return;
            }
            var aspectValidator = new AspectValidatorBuilder(e.Context.Resolve<IAspectConfiguration>()).Build();

            var b1 = services.All(x => !aspectValidator.Validate(x, true));
            var b2 = aspectValidator.Validate(limitType, false);
这里aspectValidator 判断也有问题
4.建议增加对DryIoc的支持

**Comment by SarcoZ** [comment]
补充,建议将AOP功能和DryIoc 集成

**Comment by liuhaoyang** [comment]
@huoshan12345 cc/
