### ISSUE TITLE
Process is terminating due to StackOverflowException.

### ISSUE THREAD

**Issue by kaanid** [dotnetcore/AspectCore-Framework#138]
`
var host = new HostBuilder()
    .UseConsoleLifetime()
    .UseServiceProviderFactory(new AspectCoreServiceProviderFactory())
    .ConfigureServices(serviceColl => {
        serviceColl.AddLocalServices();
        serviceColl.AddHostedService<ThriftHost>();
    })
    .Build();
`

当调用：
host.Dispose();

控制台报：Process is terminating due to StackOverflowException.

**Comment by liuhaoyang** [comment]
有异常堆栈么

**Comment by kaanid** [comment]
有一个例子，您可以看看。
惭愧，堆栈不知道怎么看

**Comment by kaanid** [comment]
已经发到hotmail,请有空查看一下。

**Comment by kaanid** [comment]
代码在这里：[点击](https://github.com/kaanid/ihostServicebyaspect)

谢谢

**Comment by liuhaoyang** [comment]
使用 .UseServiceProviderFactory(new DynamicProxyServiceProviderFactory()) 可解决问题

**Comment by kaanid** [comment]
感谢
