### ISSUE TITLE
在方法上使用NonAspectAttribute后执行时发生MethodAccessException异常。

### ISSUE THREAD

**Issue by wzd24** [dotnetcore/AspectCore-Framework#139]
接口代码：
  public interface IUnitOfWorkTestService
    {
        void TestMothodWithUnitOfWork();

        [NonAspect]
        void TestMothodWithoutUnitOfWork();

        [NonAspect]
        IActiveUnitOfWork Current { get; }
    }
添加拦截器代码：

        public static void RegisterConventionalInterceptor(IServiceCollection services)
        {
            var maps = new Dictionary<Type, TypeInterceptorMap>();
            var context = new ConventionaInterceptorContext(maps);
            Registrars.ForEach(r => r.Register(context));
            services.ConfigureDynamicProxy(c =>
            {
                maps.Values.ForEach(m =>
                {
                    services.TryAddTransient(m.InterceptorType);
                    c.Interceptors.AddServiced(m.InterceptorType, GetPredicate(m.ServiceTypes));
                });
            });

        }

        public static AspectPredicate GetPredicate(IList<Type> types)
        {
            return m =>  types.Any(t => m.DeclaringType.IsAssignableTo(t));
        }

执行TestMothodWithoutUnitOfWork代码后发生下面的异常：

System.MethodAccessException:“Attempt by method 'AspectCore.DynamicGenerated.UnitOfWorkTestService.TestMothodWithoutUnitOfWork()' to access method 'Scorpio.Uow.UnitOfWorkTestService.TestMothodWithoutUnitOfWork()' failed.”

**Comment by liuhaoyang** [comment]
能否提供可复现此问题的demo

**Comment by liuhaoyang** [comment]
能否贴一下 Scorpio.Uow.UnitOfWorkTestService 类的代码？

**Comment by wzd24** [comment]
internal class UnitOfWorkTestService : IUnitOfWorkConventionalTestService
    {
        private readonly IUnitOfWorkManager _unitOfWorkManager;

        public UnitOfWorklTestService(IUnitOfWorkManager unitOfWorkManager)
        {
            _unitOfWorkManager = unitOfWorkManager;
        }

        public IActiveUnitOfWork Current { get; set; }
        public void TestMothodWithoutUnitOfWork()
        {
            Current= _unitOfWorkManager.Current;
        }

        public void TestMothodWithUnitOfWork()
        {
            Current = _unitOfWorkManager.Current;
        }
    }

**Comment by wzd24** [comment]
我把：
var callOpCode = implementationMethod.IsCallvirt() ? OpCodes.Callvirt : OpCodes.Call;
ilGen.Emit(callOpCode, implementationMethod.IsExplicit() ? method : implementationMethod);
修改成：
//var callOpCode = implementationMethod.IsCallvirt() ? OpCodes.Callvirt : OpCodes.Call;
//ilGen.Emit(callOpCode, implementationMethod.IsExplicit() ? method : implementationMethod);
var callOpCode = OpCodes.Call;
ilGen.Emit(callOpCode, method);
后异常消失了。
