### ISSUE TITLE
能否提供类似Autofac.Extras.DynamicProxy的绑定方法?

### ISSUE THREAD

**Issue by IvanZheng** [dotnetcore/AspectCore-Framework#140]
Autofac默认的AOP组件用的是Castle.Core, 它无法很好的处理异步的AOP操作. AspectCore很好的解决了异步的问题.  我们在集成AspectCore和Autofac的时候, 发现AspectCore注册interceptor的时候是提供了全局注册, 并通过AspectPredicate来判断哪些Resolve对象是需要AOP. 这方面我觉得Autofac.Extras.DynamicProx的做法更合理些, RegistrationExtensions.InterceptedBy(registrationBuilder, interceptorType) 只作用于当前DI注册对象, AspectPredicate里面的参数是只有一个method,好像只能获取到registration的fromtype, 如果有named registration, 相同的fromType可能有不同的注册要求. 所以有没有可能提供类似Autofac.Extras.DynamicProxy 的 RegistrationExtensions.InterceptedBy(registrationBuilder, interceptorTypes)方法来注册interceptor? (而AspectCore的InterceptorAttribute对我们的应用有较大的侵入性,所以我们并不考虑使用) 
AspectCore是个很棒的项目, 非常感谢!

**Comment by liuhaoyang** [comment]
我们只提供了通用的注册，你可以自己扩展autofac的Register， 或者提出一个扩展模型来讨论怎么做更合理
