### ISSUE TITLE
案例代理不成功

### ISSUE THREAD

**Issue by ww198643** [dotnetcore/AspectCore-Framework#141]
我尝试运行/extrax/sample下的Sample，都未能拦截成功，都没有执行MethodExecuteLoggerInterceptor的Invoke方法，是我用得不对吗？我是直接下载源码运行的

**Comment by liuhaoyang** [comment]
谢谢反馈。sample 的MethodExecuteLoggerInterceptor 没有实际执行，这部分代码应该被删除的。
