### ISSUE TITLE
能否改进一下属性注入，移除在startup.cs中给mvc调用AddControllersAsServices

### ISSUE THREAD

**Issue by xiaotupansy** [dotnetcore/AspectCore-Framework#144]
如题。

现在我碰到一个问题是，如果使用代码动态生成controller，那么调用AddControllersAsServices这个方法就会报错。
另外我始终觉得，要调用AddControllersAsServices才能实现属性注入有些绕，我并不需要把controller也注册成一个服务并被其它服务访问到。

**Comment by liuhaoyang** [comment]
AddControllersAsServices  这个是asp.net core mvc框架提供的限制，不能绕过。

**Comment by xiaotupansy** [comment]
但是在hangfire中实际使用AspectCore的时候，也会发生加了AddControllersAsServices也获取不到的情形。
