### ISSUE TITLE
提议：是否可以将动态类型创建开放单独的接口？

### ISSUE THREAD

**Issue by myfp** [dotnetcore/AspectCore-Framework#145]
有些场景下我们需要动态的创建一个混合类型，大概如下
1、
```DynamicMixin<T,T1,T2>(Expression<Func<T,T1,T2,object>> mixin );
   DynamicMixin((a,b,c)=>new {a.id,b.name,c.d.nn,int xxx=3,Method1=Func<xxx>});
```
2、可以通过某种{名称，类型}集合创建一个动态类

**Comment by liuhaoyang** [comment]
AspectCore的定位只做好AOP。你的需求可以使用NCC下面的另一个项目 https://github.com/dotnetcore/Natasha

**Comment by NMSAzulX** [comment]
@myfp  I opened a new issue for this.   [goto](https://github.com/dotnetcore/Natasha/issues/7)
