### ISSUE TITLE
拦截异步方法，返回值为null

### ISSUE THREAD

**Issue by ww198643** [dotnetcore/AspectCore-Framework#147]
![image](https://user-images.githubusercontent.com/17895675/48965354-7b094b00-eff6-11e8-8fee-2c52d6036059.png)
拦截异步方法时，赋予返回值，但是在接收方法的返回值时却为空！并且返回的的Task的id与赋值的Task的id不同！难道我的用法有问题？

**Comment by ww198643** [comment]
非异步方法没有问题

**Comment by ww198643** [comment]
找到什么地方出问题了，但是没有理解为什么
`if (context.ServiceMethod.ReturnType == typeof(void) ||
				context.IsAsync() && !context.ServiceMethod.ReturnType.IsConstructedGenericType)
			{
				await next(context);
			}
`
我在拦截时做了判断，判断方法是否有返回值用到了context.ServiceMethod.ReturnType.IsConstructedGenericType  用了这个就出问题了，我改成了如下就可以了
`
if (context.ServiceMethod.ReturnType == typeof(void) ||
				context.IsAsync() && context.ServiceMethod.ReturnType != typeof(Task))
			{
				await next(context);
			}
`
但是具体是什么原因造成的我还没找到，我不太理解IsConstructedGenericType这个属性，这个属性是只读的，返回bool类型。官方说明：Gets a value that indicates whether this object represents a constructed generic type. You can create instances of a constructed generic type.

**Comment by liuhaoyang** [comment]
可以提供demo么

**Comment by ww198643** [comment]
[demo](https://github.com/ww198643/AspectCaching)
之前的赋值方式是按上面截图的方式直接赋值
目前已经解决了，解决办法是在赋值前进行类型转换
`
if (context.IsAsync())
					{
						dynamic temp = Convert.ChangeType(value, returnType);
						context.ReturnValue = Convert.ChangeType(Task.FromResult(temp), context.ServiceMethod.ReturnType);
					}
`

**Comment by liuhaoyang** [comment]
已经找到原因了。
`IAspectCaching`的函数签名是`Task<object> GetAsync(string key, Type type);` ，返回的类型是`Task<object>`，测试函数的返回类型是`Task<DateTime>`，Task<object> 和 Task<DateTime>是不能直接强转的。

**Comment by ww198643** [comment]
不能转换的时候，aspectcore就给了一个default吗？
