### ISSUE TITLE
QUESTION - Discover services that implement an interface instead of using a wild card string

### ISSUE THREAD

**Issue by codyskidmore** [dotnetcore/AspectCore-Framework#154]
Is it possible to add interceptors to a set of classes that implement an interface instead of selecting classes based on a wild card string? Example:

`config.Interceptors.AddTyped<LogInterceptor>(Predicates.ForService("*Service"));`

vs.

`config.Interceptors.AddTyped<LogInterceptor>(s => Predicates.Implements(typeof(IAuditable)));`

In the example, AddTyped() adds LogIntereceptor to every class implementing IAuditable.

**Comment by codyskidmore** [comment]
Thank you for the reply. That is the approach I previously used. It does not seem to work.

**Comment by liuhaoyang** [comment]
I've added `Implement` method https://github.com/dotnetcore/AspectCore-Framework/pull/155

**Comment by codyskidmore** [comment]
Thank you.  @liuhaoyang. I think the problem is my services are declared as:
`public async Task<IServiceResponse> MyService : IMyService, IAuditable
{
    ...
}`

MyService is registered as:
`services.AddScoped<IMyService,MyService>();`

So this works:
`config.Interceptors.AddTyped<LogInterceptor>(x=>typeof(IMyService).IsAssignableFrom(x.DeclaringType))`
because IMyService is registered with the container.

This code finds all services that implement IAuditable in addition to other interfaces.
`            List<ServiceDescriptor> auditables = new List<ServiceDescriptor>();
            foreach (ServiceDescriptor service in services)
            {
                if (service.ImplementationType != null &&
                    service.ImplementationType.GetInterfaces().Any(i => i == typeof(IAuditable)))
                {
                    auditables.Add(service);
                }
            }
`

If I could do the following, it would work.
`AddType<ILogInterceptor>(auditables)`

**Comment by codyskidmore** [comment]
Here is my work around.
```C#
            List<ServiceDescriptor> auditables = new List<ServiceDescriptor>();
            foreach (ServiceDescriptor service in services)
            {
                if (service.ImplementationType != null &&
                    service.ImplementationType.GetInterfaces().Any(i => i == typeof(IAuditable)))
                {
                    auditables.Add(service);
                }
            }
            services.ConfigureDynamicProxy(config =>
            {
                config.Interceptors.AddTyped<LogInterceptor>(x =>
                    auditables.Any(a => a.ImplementationType.GetInterfaces().Any(i => i == x.DeclaringType)));
            });
```

**Comment by liuhaoyang** [comment]
AspectCore will only create proxy classes above the serviceType `inheritance chain`.
For your example, `public class MyService : IMyService, IAuditable `,  IMyService & IAuditable on two different inheritance chains, they don't share the same dynamic proxy class.
