### ISSUE TITLE
QUESTION: 请问在dotnet core的console程序里应该如何应该如何使用AspectCore，是否可以提供简单的示例，谢谢！

### ISSUE THREAD

**Issue by eightrivers** [dotnetcore/AspectCore-Framework#157]
如果不是写基于asp.net core的web程序，而是一个dotnet core的console程序（后续会包装成一个运行在linux上的service），应该如何使用AspectCore以使用AOP的效果，可否分享一份示例代码，谢谢！

**Comment by ElderJames** [comment]
通用主机

**Comment by liuhaoyang** [comment]
请参考 [DependencyInjection.ConsoleSample](https://github.com/dotnetcore/AspectCore-Framework/tree/master/extras/sample/AspectCore.Extensions.DependencyInjection.ConsoleSample)

**Comment by eightrivers** [comment]
谢谢及时解答！！

这个例子描述的是dependency injection的场景。是否可以有一个sample说明如何在console程序里使用AbstractInterceptorAttribute。 我自己写了一小段代码，代码里的CustomInterceptorAttribute没有能够拦截住，麻烦看看可以如何调整，谢谢了！

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            new C1().Method1();
            Console.ReadLine();
        }
    }

    public class C1
    {
        [CustomInterceptor()]
        internal void Method1()
        {
            Console.WriteLine("Method1");
        }
    }

    public class CustomInterceptorAttribute : AbstractInterceptorAttribute
    {
        public async override Task Invoke(AspectContext context, AspectDelegate next)
        {
            try
            {
                Console.WriteLine("Before service call");
                await next(context);
            }
            catch (Exception)
            {
                Console.WriteLine("Service threw an exception!");
                throw;
            }
            finally
            {
                Console.WriteLine("After service call");
            }
        }
    }
}
![2019-03-10_20-51-21](https://user-images.githubusercontent.com/1868294/54085208-51dab380-4376-11e9-834b-5492bb5d8d22.jpg)
