### ISSUE TITLE
是否可以支持命名注入

### ISSUE THREAD

**Issue by gongjie18675517757** [dotnetcore/AspectCore-Framework#160]
如:
//使用类型注册服务
services.AddType<ILogger, ALogger>("ALog");
services.AddType<ILogger, BLogger>("BLog1");

//解析单个服务
ISampleService sampleService = serviceResolver.Resolve<ILogger>("ALog");
ISampleService sampleService = serviceResolver.Resolve<ILogger>("BLog");

这在某些场景下非常有用

**Comment by alexinea** [comment]
Hi @gongjie18675517757 ，具名注入在技术上并不是难题，不过考虑到要与MSDI的兼容，所以在 AspectCoreInjector 中并没有添加对具名的兼容。而且具名注入更多是用在服务定位模式中，而我们知道服务定位模式是一种不太推荐的反模式。

 @liuhaoyang ，我们以前讨论过是否需要支持具名注入这个话题，我们当时的结论是把这个需求给否掉了。

**Comment by gongjie18675517757** [comment]
了解了,谢谢解答
