### ISSUE TITLE
I have questions. 

### ISSUE THREAD

**Issue by codyskidmore** [dotnetcore/AspectCore-Framework#163]
Do you provide paid support?

Can we get documentation in English?

When using the ASP.NET Core IoC container, how to we call container.Interceptors.AddTyped() with a scoped lifetime?

**Comment by SychevIgor** [comment]
Totally agree with @codyskidmore  - it would be nice to have documentation on english!

**Comment by nicolastakashi** [comment]
Hi folks!

Great Job with this project.

We can help you translate the docs to English and other languagens maybe,

**Comment by liuhaoyang** [comment]
> Do you provide paid support?
> 
> Can we get documentation in English?
> 
> When using the ASP.NET Core IoC container, how to we call container.Interceptors.AddTyped() with a scoped lifetime?

You also need to add a custom interceptor to the serviceCollection using the scoped lifetime
