### ISSUE TITLE
AspectCore 不支持 ConfigureTestServices 

### ISSUE THREAD

**Issue by VincentYan2018** [dotnetcore/AspectCore-Framework#164]
由于使用AspectCore ConfigureServices的返回值不能够设置为void。
在使用 ConfigureTestServices 会注册一个 IStartupConfigureServicesFilter 造成抛出如下异常：
A ConfigureServices method that returns an IServiceProvider is not compatible with the use of one or more IStartupConfigureServicesFilter. Use a void returning ConfigureServices method instead or a ConfigureContainer method.
异常抛出位置为：
https://github.com/aspnet/Hosting/blob/cfe9b26a34af15c4943240d790ee5d1a168290c9/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs#L185
我会使用ConfigureTestServices来动态修改测试中的一些依赖
public class CustomWebApplicationFactory<TStartup>: WebApplicationFactory<TStartup> where TStartup : class
{
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureTestServices(services => {
            services.AddScheme<TestAuthenticationOptions, TestAuthentication>("Test", null);
        });
    }
}
有没有什么办法更改我测试环境的依赖注入？

**Comment by liuhaoyang** [comment]
.NET Core版本是多少？

**Comment by VincentYan2018** [comment]
.Net Core 版本2.2.0

**Comment by liuhaoyang** [comment]
可以提供一个demo么

**Comment by liuhaoyang** [comment]
可以尝试
```
Host.CreateDefaultBuilder(args).UseServiceProviderFactory(new DynamicProxyServiceProviderFactory());
```
