### ISSUE TITLE
接口中方法的定义,如果有字符类型就报错

### ISSUE THREAD

**Issue by kuiyu** [dotnetcore/AspectCore-Framework#165]
例 
``
public interface IMyService
{
        bool ff(string a);
}

public class MyService:IMyService
{
        public bool ff(string a)
      {
          return true;
      }   
}
``
抛异常AspectCore.DynamicProxy.AspectInvocationException:“Exception has been thrown by the aspect of an invocation. ---> Common Language Runtime detected an invalid program..”

InvalidProgramException: Common Language Runtime detected an invalid program.

**Comment by liuhaoyang** [comment]
我根据你的例子测试了一下
```
class Program
    {
        static void Main(string[] args)
        {
            var builder  = new ProxyGeneratorBuilder();
            var gen = builder.Build();
            var service = gen.CreateInterfaceProxy<IMyService, MyService>();
            Console.WriteLine(service.ff("hello"));
        }
    }

    public class ServiceInterceptor : AbstractInterceptorAttribute
    {
        public override async Task Invoke(AspectContext context, AspectDelegate next)
        {
            Console.WriteLine(context.Parameters[0]);
            await next(context);
            context.ReturnValue = false;
        }
    }
    
    [ServiceInterceptor]
    public interface IMyService
    {
        bool ff(string a);
    }

    public class MyService:IMyService
    {
        public bool ff(string a)
        {
            return true;
        }
    }
```

输出：
![image](https://user-images.githubusercontent.com/10701915/56200826-2b452200-6072-11e9-9529-2947c9ebbe35.png)

**Comment by kuiyu** [comment]
我使用的是asp.net core , 
 public static IServiceProvider GetServiceProvider(this IServiceCollection services)
        {
            var container= services.ToServiceContainer();
           container.AddDataAnnotations();             
            return container.Build(); 
        } 

发现如果添加 验证 container.AddDataAnnotations();  这句,
结果就会抛异常AspectCore.DynamicProxy.AspectInvocationException:“Exception has been thrown by the aspect of an invocation. ---> Common Language Runtime detected an invalid program..”

InvalidProgramException: Common Language Runtime detected an invalid program.
