### ISSUE TITLE
有空改下使用指南吧 ，方法被弃用了 。

### ISSUE THREAD

**Issue by BigBigPlant** [dotnetcore/AspectCore-Framework#167]
顺便问下，用AspectCore必须使用你的AspectCore.Injector吗，能否用微软自带的这个IOC容器？

**Comment by liuhaoyang** [comment]
> 顺便问下，用AspectCore必须使用你的AspectCore.Injector吗，能否用微软自带的这个IOC容器？

使用MSDI请参考https://github.com/dotnetcore/AspectCore-Framework/blob/master/extras/sample/AspectCore.Extensions.DependencyInjection.Sample/Startup.cs#L33
