### ISSUE TITLE
AddDataAnnotations报错

### ISSUE THREAD

**Issue by kuiyu** [dotnetcore/AspectCore-Framework#168]
接口定义只要有字符串就会报异常
在asp.net core中
``
public interface IMyService
{
bool ff(string a);
}

public class MyService:IMyService
{
public bool ff(string a)
{
return true;
}
}
``

```
public static IServiceProvider GetServiceProvider(this IServiceCollection services)
{
var container= services.ToServiceContainer();
container.AddDataAnnotations();
return container.Build();
}
```

**发现添加 container.AddDataAnnotations(); 这句,**
结果就会抛异常AspectCore.DynamicProxy.AspectInvocationException:“Exception has been thrown by the aspect of an invocation. ---> Common Language Runtime detected an invalid program..”

InvalidProgramException: Common Language Runtime detected an invalid program.

**Comment by liuhaoyang** [comment]
fixed https://github.com/dotnetcore/AspectCore-Framework/pull/169
