### ISSUE TITLE
NoSyncContextScope中设置了SynchronizationContext.Current为null,在.net core中无论时控制台程序还是asp.net core web程序中SynchronizationContext都已不起作用。因此是否应该加入条件编译？

### ISSUE THREAD

**Issue by lv-conner** [dotnetcore/AspectCore-Framework#170]
internal static class NoSyncContextScope
    {
        // See: https://stackoverflow.com/questions/28305968/use-task-run-in-synchronous-method-to-avoid-deadlock-waiting-on-async-method
        private static IDisposable Enter()
        {
            var context = SynchronizationContext.Current;
            SynchronizationContext.SetSynchronizationContext(null);
            return new Disposable(context);
        }

        private struct Disposable : IDisposable
        {
            private readonly SynchronizationContext _synchronizationContext;

            public Disposable(SynchronizationContext synchronizationContext)
            {
                _synchronizationContext = synchronizationContext;
            }

            public void Dispose() =>
                SynchronizationContext.SetSynchronizationContext(_synchronizationContext);
        }

        public static void Run(Task task)
        {
            using (Enter())
            {
                task.GetAwaiter().GetResult();
            }
        }

        public static T Run<T>(Task<T> task)
        {
            using (Enter())
            {
                return task.GetAwaiter().GetResult();
            }
        }
    }

**Comment by lv-conner** [comment]
部分参考：https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html

**Comment by liuhaoyang** [comment]
赞同 。下个版本会优化。
