### ISSUE TITLE
当拦截器拦截的是一个同步方法，由于内部拦截器Pipeline是通过Task实现，最终会导致在同步方法中阻塞等待异步方法，导致CLR创建大量线程，最终导致应用程序无响应的问题。

### ISSUE THREAD

**Issue by lv-conner** [dotnetcore/AspectCore-Framework#171]
NoSyncContextScope类中的：
        public static void Run(Task task)
        {
            using (Enter())
            {
                task.GetAwaiter().GetResult(); //此处会阻塞线程。在高并发的情况下将阻塞大量的线程。
            }
        }

**Comment by lv-conner** [comment]
拦截同步方法，而拦截器内部为异步实现，因此最终会导致在同步方法中等待异步方法，导致以下问题：
https://www.cnblogs.com/dudu/p/9860959.html

**Comment by liuhaoyang** [comment]
相当于你在同步方法中调用异步函数，也是不推荐的一种方式。

**Comment by lv-conner** [comment]
> 相当于你在同步方法中调用异步函数，也是不推荐的一种方式。

也就是说不推荐在同步方法中使用aspect core进行拦截？
