### ISSUE TITLE
ArgumentException: Type 'Service.IAgentUserService' should be class.

### ISSUE THREAD

**Issue by wangpengzong** [dotnetcore/AspectCore-Framework#172]
AspectCore.Core:1.2.0
Microsoft.AspNetCore.Mvc:2.2.0

VS:2017
![image](https://user-images.githubusercontent.com/29770198/58312415-d0a3a080-7e3d-11e9-9ee5-4d87af50fddb.png)

参考：https://www.cnblogs.com/liuhaoyang/p/aspectcore-getting-started.html

先上代码：
`
SampleInterceptor ：
public class SampleInterceptor : AbstractInterceptorAttribute
{
        public override Task Invoke(AspectContext context, AspectDelegate next)
        {
            Console.WriteLine("call interceptor");
            return context.Invoke(next);
        }
}

BaseService：
public class BaseService : IBaseService
{
}

IAgentUserService ：
[SampleInterceptor]
public interface IAgentUserService : IBaseService
{
        /// <summary>
        /// 用户登录
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        Result Login(AgentUserLoginRequest request);
}

AgentUserService  ：
public class AgentUserService  : BaseService, IAgentUserService
{

        #region 用户登录
        /// <summary>
        /// 用户登录
        /// </summary>
        /// <param name="request"></param>
        public Result Login(AgentUserLoginRequest request)
        {
                 return new Result();
        }
}

 #region 创建代理用户服务类
 /// <summary>
/// 创建代理用户服务类
 /// </summary>
 /// <returns></returns>
public static IAgentUserService CreateAgentUserService()
{
            ProxyGeneratorBuilder proxyGeneratorBuilder = new ProxyGeneratorBuilder();
            IProxyGenerator proxyGenerator = proxyGeneratorBuilder.Build();

            return proxyGenerator.CreateClassProxy<IAgentUserService, AgentUserService>();
}
#endregion

在实际调用时：
public async Task ValidateAsync(ResourceOwnerPasswordValidationContext context)
 {
var result = MyAgentUserService.Login(new AgentUserLoginRequest()
            {
                UserName = context.UserName,
                UserPwd = context.Password
            });
}

VS没有提示报错，但是在实际运行调用接口时会报错误：

<h1>An unhandled exception occurred while processing the request.</h1>
        <div class="titleerror">ArgumentException: Type &#x27;Service.IAgentUserService&#x27; should be class.
            <br />
Parameter name: serviceType
        </div>
        <p class="location">AspectCore.DynamicProxy.ProxyTypeGenerator.CreateClassProxyType(Type serviceType, Type implementationType)</p>
        <div class="titleerror">TypeInitializationException: The type initializer for &#x27;Api.Identity.ResourceOwnerPasswordValidator&#x27; threw an exception.</div>
        <p class="location">Api.Identity.ResourceOwnerPasswordValidator&#x2B;&lt;ValidateAsync&gt;d__2.MoveNext() in 
            <code title="D:\YlsdaiMSAProject\Api\Api.Identity\ResourceOwnerPasswordValidator.cs">ResourceOwnerPasswordValidator.cs</code>, line 23
        </p>

可以看到：Type 'Service.IAgentUserService' should be class. 但这里是和参考文档中一样的interface和SampleInterceptor，并且VS也没提示

`

**Comment by liuhaoyang** [comment]
创建接口代理请使用 CreateInterfaceProxy
