### ISSUE TITLE
文档能更新下么？

### ISSUE THREAD

**Issue by or4ngexu** [dotnetcore/AspectCore-Framework#174]
都9012年了，文档示例全是老的，单元测试也全是用的老的接口，你们是打算让所有人加群去问吗？

**Comment by liuhaoyang** [comment]
由于此项目是由我和几个志愿者在业余时间进行维护，大家也有自己的本职工作。项目本身是开源的，也需要更多的开源爱好者来一起贡献。如果你对项目有使用心得，可以帮助更新文档。最后，加群也是一种很有效的方式。
