### ISSUE TITLE
How to send argumen to attribute?

### ISSUE THREAD

**Issue by nicolastakashi** [dotnetcore/AspectCore-Framework#175]
Hi folks!

I need to send primitive parameters to my attribute like a int or a string, but I can't do that.

Sorry if I make a mistake, but I need some help. I have a piece of code like that:

```
public class CustomInterceptorAttribute : AbstractInterceptorAttribute
    {
        public int CacheTime { get; set; }

        public CustomInterceptorAttribute(int cacheTime)
        {
            this.CacheTime = cacheTime;
        }

        public CustomInterceptorAttribute()
        {
        }

        public async override Task Invoke(AspectContext context, AspectDelegate next)
        {
            try
            {
                var key = await GetKeyCacheAsync(context);
                var a = CacheTime;              
        }
```

But when I try to see the value of `a` variable there is a default 0 value.

**Comment by liuhaoyang** [comment]
You can try the following way
```
  services.ConfigureDynamicProxy(config =>
   {
         config.Interceptors.AddTyped< CustomInterceptorAttribute >(new object[]{ 1 });
   });
```

**Comment by nicolastakashi** [comment]
But if need to override this value in each instance, for example:

```
[CustomInterceptor(CacheTime = 10)]
public void MyMethod()
{
}
```

I can't :(

Sorry if I made some mistake.

**Comment by liuhaoyang** [comment]
`MyMethod` needs to be marked as a virtual method

**Comment by nicolastakashi** [comment]
Sorry for the delay.

I make `MyMethod` as Virtual but not working.

When I access the CacheTime value in Invoke method, they have the original value.

**Comment by liuhaoyang** [comment]
Remove the default constructor
