### ISSUE TITLE
启用EnableParameterAspect()，通过Code first 生成的Mirgration出错

### ISSUE THREAD

**Issue by liu7923032** [dotnetcore/AspectCore-Framework#177]
![image](https://user-images.githubusercontent.com/6694794/61265053-5fd78f80-a7c1-11e9-9aa4-ad27d88c5bd6.png)
![image](https://user-images.githubusercontent.com/6694794/61265064-6c5be800-a7c1-11e9-84d3-16bbaa96fe8d.png)
![image](https://user-images.githubusercontent.com/6694794/61265080-7847aa00-a7c1-11e9-8c67-409cd0383a87.png)

**Comment by liuhaoyang** [comment]
已知aspectCore会和EF冲突，你可以配置忽略EF和Mirgration的类型
