### ISSUE TITLE
asp.netcore3.0 注入控制器无效

### ISSUE THREAD

**Issue by zhaoqinghai** [dotnetcore/AspectCore-Framework#178]
使用3.0preview时，不支持startup,configureservices返回iserviceprovider的方式，由于提供UseServiceProviderFactory这种方式来使用第三方依赖注入框架，我尝试使用发现无法注入controller

**Comment by liuhaoyang** [comment]
不提供demo或日志，只有一句话描述。作者也猜不到你的问题是啥哈

**Comment by zhaoqinghai** [comment]
`using System;
using AspectCore.Extensions.DependencyInjection;
using AspectCore.Injector;
using BankApi.Controllers;
using Microsoft.Extensions.DependencyInjection;

namespace BankApi.Framework
{
    public class AspectServiceProviderFactory : IServiceProviderFactory<IServiceContainer>
    {
        public IServiceContainer CreateBuilder(IServiceCollection services)
        {
            services.AddSettingConfigures();
            services.AddControllers().AddNewtonsoftJson(options => {
                options.SerializerSettings.NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore;
                options.SerializerSettings.DateTimeZoneHandling = Newtonsoft.Json.DateTimeZoneHandling.Utc;
                options.SerializerSettings.DateFormatString = "yyyy-MM-dd";
            });
            var container = services.ToServiceContainer();
            return container;
        }

        public IServiceProvider CreateServiceProvider(IServiceContainer containerBuilder)
        {
            var provider = containerBuilder.Build();
            return provider;
        }
    }
}`

`using System.IO;
using AspectCore.Injector;
using BankApi.Framework.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace BankApi.Framework
{
    public static class Extensions
    {
        public static void AddSettingConfigures(this IServiceCollection serviceCollection){
            serviceCollection.AddOptions<ConfigOption>();
        }

        public static IHostBuilder UseAspectServiceProviderFactory(this IHostBuilder hostBuilder)
        {
            hostBuilder.UseServiceProviderFactory<IServiceContainer>(new AspectServiceProviderFactory());
            return hostBuilder;
        }
    }
}`

`using System.Net.Mime;
using System.Security.Authentication;
using System.Net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BankApi.Utils;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using BankApi.Framework;
using NLog;
using NLog.Extensions.Hosting;
namespace BankApi
{
    public class Program
    {
        public static void Main(string[] args)
        {
            InitCertificate(args);
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureHostConfiguration(option =>
                {
                    option.SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                        .AddJsonFile(path: $"appsettings.json", optional: true, reloadOnChange: true);
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseKestrel(options =>
                    {
                        options.Listen(IPAddress.Loopback, 5001, configure =>
                        {
                            configure.Protocols = HttpProtocols.Http1AndHttp2;
                            configure.UseHttps(CredentialFactory.Create());
                        });
                    });
                    webBuilder.UseStartup<Startup>();
                })
                .UseAspectServiceProviderFactory()
                .UseNLog();
        
        public static void InitCertificate(string[] args) => CredentialFactory.Init(args);
    }
   
}
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspectCore.Injector;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
namespace BankApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        [FromContainer]
        private ILogger<ValuesController> Logger {get;set;}

        public ValuesController(IServiceProvider provider){
            var controller = provider.Resolve<ValuesController>();
        }
    }
}
`
我看了下controller和Logger都是空的

**Comment by zhaoqinghai** [comment]
[https://github.com/zhaoqinghai/DemoApi](url) @liuhaoyang 我写了个简单的demo

**Comment by zhaoqinghai** [comment]
不好意思 现在又可以了
