### ISSUE TITLE
动态编织-破坏了继承关系

### ISSUE THREAD

**Issue by hjkl950217** [dotnetcore/AspectCore-Framework#179]
环境: win10-x64 .net core 2.2
ioc： .net core自带的

问题：从ioc获取到接口，然后转换为抽象类时失败。
原因：

我写伪代码吧：

实现->抽象类->接口  ->是继承
ioc关系配置时,    `service.TryAddEnumerable(new ServiceDescriptor(typeof(接口), typeof(实现), ServiceLifetime.Singleton));`

使用： public xxx(IEnumerable<接口>)
            构造方法的代码中会将单个接口转换为`抽象类`使用。 这里报错了

建议：动态编织时会继承原来的实现，这样就不会破坏继承关系。目前发现是动态编织后，剩下编织的实现与接口的关系，与抽象类的关系没有了。  如果有其它考虑的话， 可以告诉我嘛？

**Comment by liuhaoyang** [comment]
接口的代理类自然不会去继承实现类原先的抽象类。
你这里正确的做法是，通过代理类拿到原始的实现类实例，再去转换成你的抽象类。
抛开动态代理，谁也不会保证你的接口都可以转换成抽象类

**Comment by hjkl950217** [comment]
后面我试试看。你说的这个点也确实是，我这里明确知道接口的实现是什么，所以才能向抽象类转换。

但是从接口与实现的关系来说，确实是没有抽象类的。
