### ISSUE TITLE
怎么对Framework的Controller进行注入？

### ISSUE THREAD

**Issue by youbl** [dotnetcore/AspectCore-Framework#183]
找了一圈，只写了Core项目里的注入支持，
issue里有个提问者，用的是autofac，
请问aspectcore原生支持Framework的Controller进行注入吗？

支持的话，要怎么实现？

**Comment by liuhaoyang** [comment]
支持。你要自己实现mvc和webapi的依赖注入接口

**Comment by youbl** [comment]
> 支持。你要自己实现mvc和webapi的依赖注入接口

感谢回复，能帮忙写个Demo吗？

**Comment by youbl** [comment]
哦哦，要自己实现webapi的注入，那就是要自己写，或改用unity 或 autofac了？
