### ISSUE TITLE
使用数组类型作为拦截器属性时，抛出

### ISSUE THREAD

**Issue by gainorloss** [dotnetcore/AspectCore-Framework#192]
![image](https://user-images.githubusercontent.com/26458238/67916514-e7120d00-fbd0-11e9-8a71-148f2a9c29ef.png)

**Comment by gainorloss** [comment]
使用默认值正常，从特性使用时进行赋值抛出如图所示是的异常

**Comment by liuhaoyang** [comment]
代码呢

**Comment by gainorloss** [comment]
/// <summary>
    /// @Test
    /// </summary>
    public class TestAttribute
           : AbstractInterceptorAttribute
    {
        public int[] Times { get; set; } = new int[] { 1, 100, 10000, 1000000 };
        public override async Task Invoke(AspectContext context, AspectDelegate next)
        {
            var sw = new Stopwatch();

            var result = new List<long>();
            foreach (var times in Times)
            {
                sw.Restart();
                for (int i = 0; i < times; i++)
                    await next(context);
                sw.Stop();
                result.Add(sw.ElapsedMilliseconds);
            }
#if DEBUG
            System.Console.WriteLine($@"【+$Test】:
{string.Join(Environment.NewLine, Times.Select((times, i) => $"执行{times}次{result[i]}ms"))}(无线电)");
#endif
        }
    }

    public interface IUserAppService
    {
        //[Test]
        [Test(Times = new int[] { 10, 100 })]
        string DisplayName(string firstName, string lastName);
    }
 public class UserAppService
        : IUserAppService
    {
        public string DisplayName(string firstName, string lastName)
        {
            var fullName = $"{firstName} {lastName}";
            return fullName;
        }
    }
入口如下：
 var sp = new ServiceCollection()
                    .AddScoped<IUserAppService, UserAppService>()
                    .ConfigureDynamicProxy()
                    .BuildAspectInjectorProvider();

                var usrAppSrv = sp.GetRequiredService<IUserAppService>();
                usrAppSrv.DisplayName("gain","loss");

**Comment by huoshan12345** [comment]
已复现，已尝试修复，待合并
