### ISSUE TITLE
.net core 3.0 使用aspectcore疑问

### ISSUE THREAD

**Issue by pan1984730** [dotnetcore/AspectCore-Framework#193]
环境.net core3.0
包：AspectCore.Extensions.Autofac
       Autofac.Extensions.DependencyInjection
       Autofac.Configuration
使用AspectCore，AOP无效。

**Comment by huoshan12345** [comment]
可否给一些能复现的样例代码

**Comment by xxdqr** [comment]
楼上应该贴出来组件的版本

**Comment by lovredo** [comment]
在.net core 3.1 使用autofac结合aspectcore时，builder.RegisterDynamicProxy() 报错：Method not found: 'Autofac.Builder.DeferredCallback Autofac.ContainerBuilder.RegisterCallback(System.Action`1<Autofac.Core.IComponentRegistry>)'.

**Comment by huoshan12345** [comment]
@lovredo @pan1984730 请升级aspectcore到2.1.0+版本，已经决解了和新版autofac的适配问题
