### ISSUE TITLE
2.0版本的Nuget包好像不支持FromContainer了，不知道是不是打包打错了？

### ISSUE THREAD

**Issue by wadereye** [dotnetcore/AspectCore-Framework#200]
原来用1.3版本的nuget包正常运行的程序，升级到2.0以后。
命名空间已经没有AspectCore.Injector;
FromContainer属性编译报错，不知道 是打包的问题，还是2.0改动太大？我将原来的sample下载下来。看到是用的0.3的版本。

**Comment by huoshan12345** [comment]
- FromContainer改为FromServiceContext了

- 命名空间有变化。

- 2.0改动有很多

先关闭了，如果还有问题重开

**Comment by wadereye** [comment]
感谢
