### ISSUE TITLE
[FromServiceContext]在服务里使用正常，在Controller里使用不正常，请问是什么原因

### ISSUE THREAD

**Issue by yus1977** [dotnetcore/AspectCore-Framework#211]

**Comment by huoshan12345** [comment]
可否提供一些能复现的代码

**Comment by IMwinglee** [comment]
同问，webapi项目，api控制器中，添加[UnitOfWork]标签，无效果

**Comment by chaoyebugao** [comment]
一样的问题，在逻辑层Service正常，Controller里面用FromServiceContext注入不了，为null

**Comment by huoshan12345** [comment]
@yus1977 @IMwinglee @chaoyebugao 在`Startup`的`ConfigureServices`方法中需要调用`AddControllersAsServices`方法，例如
```
services.AddControllers()
            .AddControllersAsServices(); // 关键是这行
```
这样就可以在Controller正常使用属性注入了。
本issue先关闭了，如果有问题再重新开
