### ISSUE TITLE
请问，在Asp.NetCore3.1下如何才能使用ConfigurationBinding

### ISSUE THREAD

**Issue by yus1977** [dotnetcore/AspectCore-Framework#212]
我按Test的示例
        public void ConfigureContainer(IServiceContext builder)
        {
            builder.AddInstance<IConfiguration>(Configuration);
            builder.AddConfigurationInject();
            builder.AddType<MyContext>();
        }
但是没有成功

**Comment by GeorGeWzw** [comment]
在.Net Core3.1中使用方式换了不需要使用你上面的方式
