### ISSUE TITLE
Exception has been thrown by the aspect of an invocation. ---> Constructor on type 'AOP.GlobalAopTran' not found..

### ISSUE THREAD

**Issue by GeorGeWzw** [dotnetcore/AspectCore-Framework#219]
您好，请问一下是不是在.Net Core3.1中需要使用AbstractInterceptorAttribute特性来进行继承；而不是使用AbstractInterceptor这个类了；我继承AbstractInterceptor报错Exception has been thrown by the aspect of an invocation. ---> Constructor on type 'AOP.GlobalAopTran' not found.. 无法找到构造函数；以下是我的使用方式
![QQ截图20200420203707](https://user-images.githubusercontent.com/46982191/79752625-3696f180-8347-11ea-80f7-cc734544d5c9.png)

**Comment by huoshan12345** [comment]
因为你这个Interceptor依赖了接口，所以不能用config.Interceptors.AddTyped，因为这个是使用无参构造函数创建Interceptor实例的。
你这个Interceptor需要从DI容器里面取，所以先把Interceptor注册到DI容器里，然后config.Interceptors.AddServiced就可以了。

或者直接这样，就可以用AddTyped了（注意AddTyped的过滤条件）
```
public class UnitOfWorkInterceptor : AbstractInterceptor
{
    public override async Task Invoke(AspectContext context, AspectDelegate next)
    {
        var unitOfWork = context.ServiceProvider.GetRequiredService<IUnitOfWork>();
        unitOfWork.Begin();
        await context.Invoke(next);
        unitOfWork.Commit();
    }
}
```

**Comment by GeorGeWzw** [comment]
好的，已经解决了，谢谢回复
