### ISSUE TITLE
如何在asp.net core的controller中使用AspectCore.Extensions.DataValidation进行参数验证

### ISSUE THREAD

**Issue by leyou240** [dotnetcore/AspectCore-Framework#221]
如题！

**Comment by huoshan12345** [comment]
@leyou240 
关键点就是`DataValidationInterceptorAttribute`这个Interceptor的使用。
具体使用可以参考
https://github.com/dotnetcore/AspectCore-Framework/tree/master/sample/AspectCore.Extensions.DataAnnotations.Sample

这个issue先关闭了，如果你还有使用上的问题，可以再重开
