### ISSUE TITLE
AspectCore.DynamicProxy无法代理到类库下文件夹中的类；

### ISSUE THREAD

**Issue by GeorGeWzw** [dotnetcore/AspectCore-Framework#222]
在使用AspectCore.DynamicProxyAOP代理时因为项目需要 要根据业务建相映的文件夹，在使用过程中发现DP只能识别到类库直属的类，而不能识别到类库文件夹中的类；建议做着修复一下例如
![图片](https://user-images.githubusercontent.com/46982191/80312221-980f0280-8816-11ea-8b49-9b8d11f159e4.png)

**Comment by huoshan12345** [comment]
@GeorGeWzw 可否提供一些具体能复现的代码，比如用的什么容器，怎么创建容器的，怎么注入服务的，怎么启用AspectCore.DynamicProxy的

**Comment by GeorGeWzw** [comment]
![QQ截图20200803074128](https://user-images.githubusercontent.com/46982191/89135127-cf035b80-d55d-11ea-8f44-ed2895bb1107.png)
![QQ截图20200803074219](https://user-images.githubusercontent.com/46982191/89135130-d0cd1f00-d55d-11ea-8978-07f2ca553b7a.png)
![QQ截图20200803074807](https://user-images.githubusercontent.com/46982191/89135131-d0cd1f00-d55d-11ea-99a7-6e8714a9446e.png)
![QQ截图20200803074857](https://user-images.githubusercontent.com/46982191/89135132-d165b580-d55d-11ea-8fed-75d0932f1aeb.png)

**Comment by huoshan12345** [comment]
@GeorGeWzw 
设计如此。如果你想打到你的目的，需要使用通配符`*`
例如
```
Predicates.ForNameSpace("Microsoft.EntityFrameworkCore");      // 匹配命名空间为Microsoft.EntityFrameworkCore
Predicates.ForNameSpace("Microsoft.EntityFrameworkCore.*");    // 匹配命名空间以Microsoft.EntityFrameworkCore开头的，例如Microsoft.EntityFrameworkCore.Tests 或者Microsoft.EntityFrameworkCore.Tests.AnyTest

Predicates.ForNameSpace("Microsoft.EntityFrameworkCore*");     // 匹配上面两种情况
```
所以你在命名空间后面加个星号就行了。

issue先关闭了，有问题再重开
