### ISSUE TITLE
aspectcore CustomInterceptorAttribute invoke not working

### ISSUE THREAD

**Issue by lmxin123** [dotnetcore/AspectCore-Framework#224]
I use asp.net core 3.1,my core like this:

public class CustomInterceptorAttribute : AbstractInterceptorAttribute
    {
        public override async Task Invoke(AspectContext context, AspectDelegate next)
        {
            try
            {
                Console.WriteLine("Before service call");
                await next(context);
            }
            catch (Exception)
            {
                Console.WriteLine("Service threw an exception!");
                throw;
            }
            finally
            {
                Console.WriteLine("After service call");
            }
        }
    }
-----------------------
public interface ICustomService
    {
        [CustomInterceptor]
        void Call(string p);
    }

    public class CustomService : ICustomService
    {
        public void Call(string p)
        {
            Console.WriteLine("service calling...");
        }
    }
--------------Add Setup like this
    services.ConfigureDynamicProxy(config =>
            {
                config.Interceptors.AddTyped<CustomInterceptorAttribute>();
            });
            services.AddSingleton<ICustomService, CustomService>();
------------this is my controller 
 public class DefaultController : Controller
    {
        private readonly ICustomService _customService;
        public DefaultController(ICustomService customService)
        {
            _customService = customService;
        }
        public IActionResult Index()
        {
            _customService.Call("test AspectCore");
            return View();
        }
    }
When I debug,CustomInterceptorAttribute Invoke not working.
Just print "service calling...".
What's wrong？

**Comment by huoshan12345** [comment]
@lmxin123 `因为默认的Startup代码逻辑里把`IServiceCollection`构建成`ServiceProvider`会调用`BuildServiceProvider``方法，但这个方法是无法使得AspectCore的动态代理生效的。你需要使用AspectCore内置的`ServiceContextProviderFactory`类来控制容器构建方法。可以调用`public static IHostBuilder UseServiceContext(this IHostBuilder hostBuilder)`这个方法。
我先关闭这个issue了，如果还是没解决你的问题，你就再重开这个issue
