### ISSUE TITLE
AspectCore DynamicProxy for Blazor failed

### ISSUE THREAD

**Issue by JMPlus2015** [dotnetcore/AspectCore-Framework#225]
**在Blazor（wasm client模式--客户端）中使用代理失败.**
使用方式：
`var builder = new ProxyGeneratorBuilder();
AspectCore.DynamicProxy.IProxyGenerator proxyGenerator = builder.Build();`

上述代码报错内容（可能是CustomAttributeReflector--IL问题？）：
![image](https://user-images.githubusercontent.com/17829409/82546183-4db94100-9b8a-11ea-9bb5-0f2f6725458a.png)

**Comment by huoshan12345** [comment]
@JMPlus2015 可否提供可以复现的代码。比如
```
var builder = new ProxyGeneratorBuilder(); 
// 这中间的代码具体是怎么配置的
// Interceptor怎么写的，怎么添加的
// Service又是怎么引用Interceptor的
AspectCore.DynamicProxy.IProxyGenerator proxyGenerator = builder.Build();
```

**Comment by liuhaoyang** [comment]
在.NET 5 下创建新的WASM项目没有复现。
