### ISSUE TITLE
AspectCore在做AOP动态代理时无法代理到文件夹内的接口或者方法？

### ISSUE THREAD

**Issue by GeorGeWzw** [dotnetcore/AspectCore-Framework#229]
AspectCore在做AOP动态代理时无法代理到文件夹内的接口或者方法？请问一下是设计就是如此还是说是Bug例如，我的类库这样子，我必须把文件夹内类的命名空间改变到类库下面才可以实现代理，否则代理不成功！

**Comment by huoshan12345** [comment]
可以参考https://github.com/dotnetcore/AspectCore-Framework/issues/222
