### ISSUE TITLE
如何在Controller拦截器中获取HTTPContext？

### ISSUE THREAD

**Issue by Removable** [dotnetcore/AspectCore-Framework#233]
[#16](https://github.com/dotnetcore/AspectCore-Framework/issues/16) 中提到的方法似乎已经失效。

或者有没有其他方法实现当数据或身份验证失败时，直接返回相应的Http Status Code？

谢谢

**Comment by hjkl950217** [comment]
可以使用`IHttpContextAccessor`去获取当前线程中的`HttpConetxt`。注册方法是在服务注册中: `services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();`.  

因为它是获取线程中的HttpConetxt,所以肯定是可以的。 然后aspectCore中写的拦截器，不是可以获取到DI实例么？从DI实例中取到它，就能取到了。

理论上它在其它接口上也能用，但其它接口注册实现时，可能是单例的，所以有风险哦~

最后，如果只是想在controller中实现身份验证一类的，建议使用mvc自带的filter一样能实现效果的

**Comment by Removable** [comment]
> 可以使用`IHttpContextAccessor`去获取当前线程中的`HttpConetxt`。注册方法是在服务注册中: `services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();`.
> 
> 因为它是获取线程中的HttpConetxt,所以肯定是可以的。 然后aspectCore中写的拦截器，不是可以获取到DI实例么？从DI实例中取到它，就能取到了。
> 
> 理论上它在其它接口上也能用，但其它接口注册实现时，可能是单例的，所以有风险哦~
> 
> 最后，如果只是想在controller中实现身份验证一类的，建议使用mvc自带的filter一样能取到httpContext

谢谢~
