### ISSUE TITLE
System.InvalidOperationException: Code supposed to be unreachable.

### ISSUE THREAD

**Issue by 280780363** [dotnetcore/AspectCore-Framework#236]
## issue描述:

当继承自`AbstractInterceptorAttribute`类型,并且构造函数使用了 `params object[] values`参数时,将得到` System.InvalidOperationException: Code supposed to be unreachable.`异常信息.

## 示例代码详见附件:
[WebApplication.zip](https://github.com/dotnetcore/AspectCore-Framework/files/5442417/WebApplication.zip)

**Comment by liuhaoyang** [comment]
已修复 https://github.com/dotnetcore/AspectCore-Framework/pull/253
