### ISSUE TITLE
为什么AspectCore和Autoface结合起来使用效率特别差？

### ISSUE THREAD

**Issue by zl33842901** [dotnetcore/AspectCore-Framework#239]
我的方法里注入了50个服务，像这样：
`        public void TestCommonRepository()
        {
            IContainer container = PrepareContainerByAutofaceWithAspectCore(true);
            Stopwatch sw = new Stopwatch();
            sw.Start();
            var scope = container.BeginLifetimeScope();
            List<Object> lo = new List<object>();
            foreach(var t in GetRepositories().Take(50))
                lo.Add(scope.Resolve(t));
            sw.Stop();
        }`
sw计时 5到8秒。
然后我改为使用微软自带的DI，结合 AspectCore：
`        public void TestCommonRepository2()
        {
            var container = PrepareServiceProviderByMsDIWithAspectCore();
            Stopwatch sw = new Stopwatch();
            sw.Start();
            var scope = container.CreateScope();
            List<Object> lo = new List<object>();
            foreach (var t in GetRepositories().Take(50))
                lo.Add(scope.ServiceProvider.GetService(t));
            sw.Stop();
        }`
sw计时约 50到70毫秒。
这差的也太多了，请问是为什么呢？ 结合 Autoface 的方式有性能改进计划么？

**Comment by nivalxer** [comment]
这个可能是autofac的问题。autofac在6.0版本进行了升级，改进了注册效率。
试了一下在.netcoreapp3.1，Release模式，使用System.Reflection.Emit动态生成50个类，分别使用给出的代码进行测试。
autofac5.2：
PrepareContainerByAutofaceWithAspectCore:30毫秒
PrepareServiceProviderByMsDIWithAspectCore:13毫秒

autofac6.0：
PrepareContainerByAutofaceWithAspectCore:13毫秒
PrepareServiceProviderByMsDIWithAspectCore:14毫秒
