### ISSUE TITLE
在.net core5.0中将Autofac.Extensions.DependencyInjection升级到6.0以上就会出现异常（6.0正常）

### ISSUE THREAD

**Issue by totoo1024** [dotnetcore/AspectCore-Framework#240]
An error occurred while starting the application.
MissingMethodException: Method not found: 'Void Autofac.Core.IComponentRegistration.add_Activating(System.EventHandler`1<Autofac.Core.ActivatingEventArgs`1<System.Object>>)'.
AspectCore.Extensions.Autofac.ContainerBuilderExtensions.Registry_Registered(object sender, ComponentRegisteredEventArgs e)

MissingMethodException: Method not found: 'Void Autofac.Core.IComponentRegistration.add_Activating(System.EventHandler`1<Autofac.Core.ActivatingEventArgs`1<System.Object>>)'.
AspectCore.Extensions.Autofac.ContainerBuilderExtensions.Registry_Registered(object sender, ComponentRegisteredEventArgs e)
Autofac.Core.Registration.ComponentRegistryBuilder.add_Registered(EventHandler<ComponentRegisteredEventArgs> value)
AspectCore.Extensions.Autofac.ContainerBuilderExtensions+<>c.<RegisterDynamicProxy>b__2_0(IComponentRegistryBuilder registryBuilder)
Autofac.ContainerBuilder.Build(IComponentRegistryBuilder componentRegistry, bool excludeDefaultModules)
Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
Autofac.Extensions.DependencyInjection.AutofacServiceProviderFactory.CreateServiceProvider(ContainerBuilder containerBuilder)
Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter<TContainerBuilder>.CreateServiceProvider(object containerBuilder)
Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
Microsoft.Extensions.Hosting.HostBuilder.Build()

请问一下这是什么原因导致的？应该怎么解决

**Comment by q7164518** [comment]
Autofac更新导致的, 现在还没适配Autofac新版, 我也在纠结这个问题

**Comment by liuhaoyang** [comment]
等待新版本发布会修复和autofac6.0的兼容问题
