### ISSUE TITLE
能否支持.net framework 4.5.2

### ISSUE THREAD

**Issue by zc910704** [dotnetcore/AspectCore-Framework#247]
想利用这个实现项目的AOP日志，但是现有项目只支持.net framework 4.5.2，请问可否支持。

**Comment by liuhaoyang** [comment]
目前最低支持.NETFramework 4.6.1了。

**Comment by zc910704** [comment]
> 目前最低支持.NETFramework 4.6.1了。

抱歉没有描述的特别清楚，我知道这个只支持到Framework4.6.1，因为 4.5.2的framework的版本 .Net Stadard版本不够，想问下有没有可能在452的版本上实现，是哪些导致。
