### ISSUE TITLE
Compile error for the latest solution

### ISSUE THREAD

**Issue by wangliguokaka** [dotnetcore/AspectCore-Framework#31]
after download and compile the latest version "AspectCore.Extensions.DependencyInjection" solution，there is the error such as “CS0246	未能找到类型或命名空间名“AspectCoreOptions”(是否缺少 using 指令或程序集引用?)”.
I think the version from nuget server is not the latest, please confrim it, thank you.

**Comment by liuhaoyang** [comment]
The dev branch is being reconstructed. switch to the [0.1.2](https://github.com/dotnetcore/AspectCore-Framework/tree/0.1.2) branch,it is stable and the same as the 0.1.2 version of nuget latest version.

**Comment by liuhaoyang** [comment]
The dev branch is being reconstructed. switch to the [0.1.2](https://github.com/dotnetcore/AspectCore-Framework/tree/0.1.2) branch,it is stable and the same as the [0.1.2](https://www.nuget.org/packages/AspectCore.Extensions.DependencyInjection/0.1.2) version of nuget latest version.

**Comment by wangliguokaka** [comment]
I have switch to the 0.1.2 version, the new issue occured. 
not found the interface I"InterceptorActivator"
in the solution "AspectCore.Core" , I have found this interface, so  I think the nuget package should be published  again. thank you.

**Comment by wangliguokaka** [comment]
No thanks, thank you for your great work. Learn from you.

**Comment by wangliguokaka** [comment]
sorry, this issue is fixed，but the problem remains unresolved，please confirm it. thank you

**Comment by liuhaoyang** [comment]
In the 0.2-preview1 version, `IInterceptorActivator` has been moved to [Abstractions](https://github.com/dotnetcore/AspectCore-Framework/blob/dev/src/Abstractions/src/AspectCore.Abstractions/Interceptors/IInterceptorActivator.cs), and the refactoring is still in progress. You can use the following source to see the latest changes :
```
https://www.myget.org/F/aspectcore/api/v3/index.json
```

**Comment by liuhaoyang** [comment]
@wangliguokaka 0.1.2 version is just a transitional version , because it has some bugs and does not support .net core 2.0 .  In the 0.2-preview1, in addition to bug fixes, we also refactored a high-performance [reflection library](https://github.com/dotnetcore/AspectCore-Framework/tree/dev/src/Reflection), and will increase the built-in IoC and object mapper.

**Comment by wangliguokaka** [comment]
thank you for your feedback, for the .net core 2.0 version, just ot wait for the issue to be repaired？

**Comment by liuhaoyang** [comment]
@wangliguokaka  yeap~

**Comment by liuhaoyang** [comment]
This issue has been fixed. see https://github.com/dotnetcore/AspectCore-Framework/issues/42
