### ISSUE TITLE
启动性能问题

### ISSUE THREAD

**Issue by huxingye** [dotnetcore/AspectCore-Framework#314]
EnableParameterAspect 开启以后。
当应用程序业务庞大后，有定义大量接口参数拦截， 拦截后验证参数规范性的使用场景。
启动的时候，就会等待很长时间。
非常影响调试开发。
生产的时候项目启动也非常慢。

能否优化呢？

**Comment by liuhaoyang** [comment]
应该是启动的时候加载了太多的程序集和类到DI里面，要自己加条件过滤哪些类需要 EnableParameterAspect 而不是默认全部的类都使用ParameterInterceptor

**Comment by liuhaoyang** [comment]
跟 @UtilCore 讨论后，缩小了需要做AOP的类范围，启动时间已经大幅度减少了。
非 AspectCore 框架问题。

**Comment by huxingye** [comment]
@liuhaoyang 
感谢，这个EnableParameterAspect 方法可以解决问题。
已经添加了很多过滤，缩小了范围。
目前启动时间大幅降低。额
