### ISSUE TITLE
Functional requirements for AspectCore.Extensions.Mapper

### ISSUE THREAD

**Issue by alexinea** [dotnetcore/AspectCore-Framework#32]
As this issue's title said, when mapping to TDestination, it will be able to automatically inject the dependencies in constructor.

thx. 💌

**Comment by yuleyule66** [comment]
Hi @alexinea, I think this feature we need to consider whether we really need it. Most of the time we are mapping an object with an empty constructor.

**Comment by liuhaoyang** [comment]
I think this is a necessary feature, even if  most of the time we are mapping an object with an empty constructor.

**Comment by alexinea** [comment]
@yuleyule66 A common situation is inject a repository or a specific instance witch inherits from certain interface into one model (like ddd-model, operator-wrapper, processor-wrapper, etc.). The common characteristics of these models are they have not a parameter-less constructor.

**Comment by ElderJames** [comment]
Based on my experience, however, I must define a empty constructor in the class haven't empty constructor, because most of  ORM or Serializer doesn't support mapping an object with no empty constructor.

The case like below:

```
public class TodoAggregateRoot
{
        public TodoAggregateRoot() : this(Guid.Empty)
        {
        }

        public TodoAggregateRoot(Guid aggregateId) : base(aggregateId)
        {
        }
}
```
