### ISSUE TITLE
使用方法代理的属性拦截？

### ISSUE THREAD

**Issue by liuhaoyang** [dotnetcore/AspectCore-Framework#40]
在属性的get或set标记方法拦截器即为该属性拦截器？或者重写定义属性拦截器接口？

**Comment by tzm1119** [comment]
我想在接口的属性上写拦截器，[MethodExecuteLoggerInterceptor2]是我的拦截器特性，但是创建出来的代理并没有被拦截，请问我哪里写的有问题呢？

public interface IValuesService
    {
        string Name { [MethodExecuteLoggerInterceptor2]get; [MethodExecuteLoggerInterceptor2]set; }
        IEnumerable<string> GetAll();
    }

    public class ValuesService : IValuesService
    {
        public virtual string Name { get; set; }

        public IEnumerable<string> GetAll()
        {
            this.Name = "ok";
            var b = this.Name;
            return new string[] { "11111111111", "value" };
        }
    }

**Comment by liuhaoyang** [comment]
通过接口实现的代理，在实现类内部调用函数，并不会触发拦截。这个是C#的语法限制。

**Comment by tzm1119** [comment]
嗯，我测试过了，确实外部调用可以实现代理。建议能把代理 的限制写个文章出来，还有哪些其他的代理限制吗?比如如果直接想 代理类的属性，属性必须是virtual

 public class ValuesService 
    {
        //类属性代理 必须是 共有的virtual,才能实现代理
        public virtual string Name { [MethodExecuteLoggerInterceptor2]get; set; }

    }
