### ISSUE TITLE
AspectCore不支持dotnetcore2.0

### ISSUE THREAD

**Issue by xcomlong** [dotnetcore/AspectCore-Framework#42]
在dotnetcore2.0使用会报错

**Comment by liuhaoyang** [comment]
https://www.nuget.org/packages/AspectCore.Core/0.2.0-preview2  使用0.2.0-preview2以上版本开始支持dotnet core2.0

**Comment by huoshan12345** [comment]
AspectCore.Extensions.DependencyInjection
这个还没有2.0能用的版本

**Comment by liuhaoyang** [comment]
@xcomlong @huoshan12345 https://www.nuget.org/packages/AspectCore.Extensions.DependencyInjection/0.2.0-preview3 AspectCore.Extensions.DependencyInjection已经发布。示例请参考 https://github.com/dotnetcore/AspectCore-Framework/blob/dev/src/Extras/sample/AspectCore.Extensions.DependencyInjection.Sample/Startup.cs#L30
