### ISSUE TITLE
最新的预览发行版没有修改AspectCore.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by xcomlong** [dotnetcore/AspectCore-Framework#43]
最新的预览发行版没有修改AspectCore.Extensions.DependencyInjection,好多以前的代码跑不通了.对了,在这里我怎么没有找到AspectCore.Extensions.DependencyInjection开源的项目代码呢,谢谢

**Comment by liuhaoyang** [comment]
@xcomlong AspectCore.Extensions.DependencyInjection已经发布 https://www.nuget.org/packages/AspectCore.Extensions.DependencyInjection/0.2.0-preview3
对微软DI的扩展包含在Extras[https://github.com/dotnetcore/AspectCore-Framework/tree/dev/src/Extras]目录下。目前我在另外的分支下开发，功能完成后会合并到dev分支。
