### ISSUE TITLE
非常感谢这次的更新

### ISSUE THREAD

**Issue by xcomlong** [dotnetcore/AspectCore-Framework#45]
非常感谢这次的更新。这个版本的代码，层次清晰，紧凑，很棒。但是样例太少了。比如字段注入，属性注入，方法注入，参数注入，返回值注入的样例太少，以至于不知道怎么使用了，只知道FromServices是对参数的注入，其他的不知道怎么使用。能抽空做个样例项目不，谢谢

**Comment by liuhaoyang** [comment]
感谢关注和支持，目前仍然在重构内部实现，重构完成后编写详细的文档和Sample。本周会尽量给你完成一个包含主要特性的Sample。有任何问题欢迎在issue反馈

**Comment by xcomlong** [comment]
希望这个包越做越好，稳定后应该会有很多人使用的，因为它使用起来太简单，方便的，实用价值很高
