### ISSUE TITLE
关于使用样例的问题

### ISSUE THREAD

**Issue by xcomlong** [dotnetcore/AspectCore-Framework#47]
你好,现在代码重构了很多了,使用样例还没有哦,都等待了一个星期了呢

**Comment by liuhaoyang** [comment]
你好，感谢关注。这是我目前的开发分支 https://github.com/AspectCore/AspectCore-Framework/tree/0.2.0-preview2/extras/sample   。在重构的同时也会逐步添加sample 。目前还有一些bug待修复 。请再稍等些时候。
