### ISSUE TITLE
关于拦截返回值为 dynamic 的异步方法时，拦截器内 await 的问题

### ISSUE THREAD

**Issue by alexinea** [dotnetcore/AspectCore-Framework#49]
以下方法：

```
[WrapperInterceptor]
public virtual dynamic DoSomeThing(){
    return DoSomeInterestingThingAsync();
}
```

其中 `DoSomeInterestingThingAsync` 返回 `Task<Lemon>` 类型的结果。

由于方法返回的是 dynamic，所以 AspectCore 会将其识别为同步方法，而不去 await 它。

因此例中的 `WrapperInterceptor` 内，`context.ReturnValue` 返回的是 `Task<Lemon>`。如果我要将这个 `Task<T>` 内的 Lemon 取出然后包装进一个包装类中，填回 ReturnValue 的话，需要判断这个 Task 是否完成执行。

这个等待的工作使用者来完成，还是由 AspectCore 内部来完成？

**Comment by liuhaoyang** [comment]
see https://github.com/dotnetcore/AspectCore-Framework/issues/51
