### ISSUE TITLE
关于 AspectContext 中提供剥离 Task<T> 返回值到 T 的建议

### ISSUE THREAD

**Issue by alexinea** [dotnetcore/AspectCore-Framework#51]
针对 #49 的情况，AspectCore 能否提供 `context.IsAsync`、`context.AsyncReturnValue` 这样的 API？

如果 AspectCore 可以提供这样的 API，那么需要考虑以下几种情况：

+ Task 的处理
+ Task<Task<Task<V>>> 的处理（包心菜）
+ Task<Task> 的处理
+ 以及 ValueTask 的处理

**Comment by liuhaoyang** [comment]
see https://github.com/dotnetcore/AspectCore-Framework/blob/dev/core/src/AspectCore.Core/DynamicProxy/Extensions/AspectContextRuntimeExtensions.cs#L63
