### ISSUE TITLE
和autofac整合有文档吗

### ISSUE THREAD

**Issue by hiwjcn** [dotnetcore/AspectCore-Framework#66]

**Comment by liuhaoyang** [comment]
可以看这篇文章  http://www.cnblogs.com/liuhaoyang/p/aspectcore-getting-started.html

**Comment by hiwjcn** [comment]
@liuhaoyang 谢谢！！！
你们应该还有维护依赖注入框架把。我还没有看。
不知道有没有执行泛型的注入。这是个很好的特性，现在在使用autofac。
看了下unity似乎实现的不太好

**Comment by liuhaoyang** [comment]
AspectCore的IoC支持泛型注入，使用方式何Autofac略有不同，autofac对泛型注册单独使用一个方法，在我们的IoC里，泛型和非泛型都可以使用AddType()方法进行注册

**Comment by hiwjcn** [comment]
我看到了 thanks for ur contribution
