### ISSUE TITLE
Performance Diagnostic

### ISSUE THREAD

**Issue by liuhaoyang** [dotnetcore/AspectCore-Framework#71]
添加性能追踪api，方便从外部调试和监控DynamicProxy创建代理类和执行方法拦截的性能

**Comment by ElderJames** [comment]
支持

**Comment by liuhaoyang** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md
