### ISSUE TITLE
属性注入失败

### ISSUE THREAD

**Issue by Basil1991** [dotnetcore/AspectCore-Framework#75]
public ValuesController(ISampleRepository repo) { }

        [FromContainer]
        public ISampleRepository repos { get; set; }
        
        其中构造函数可以获取到注入的ISampleRepository 对象,但是带有[FromContainer]的属性获取不到,
是使用的姿势不对吗,sample当中没有找到FromContainer的例子,只有在文档看到.

**Comment by liuhaoyang** [comment]
你用的DI是微软的DI还是AspectCore提供的ServiceResolver，目前两者中只有AspectCore内置的DI支持属性

**Comment by Basil1991** [comment]
1.services.AddTransient<ISampleService,ISampleService>();
   var container = services.ToServiceContainer();
   return container.Build();

2.var container = services.ToServiceContainer();
  container.AddType<ISampleService, ISampleService>();
  return container.Build();

这是我的使用方式，FromContainer无法识别

**Comment by liuhaoyang** [comment]
我没有重现你说的问题，并且写了一个属性注入的例子 https://github.com/dotnetcore/AspectCore-Framework/blob/master/extras/sample/AspectCore.Extensions.DependencyInjection.ConsoleSample/Program.cs

**Comment by zhaiweihao** [comment]
您好~~我也碰到了属性注入失败的问题。
我看了您写的ConsoleSample，但是不明白`serviceCollection.ToServiceContainer()`是哪的方法。是扩展的吗，我看ServiceCollection没有这个方法。

**Comment by liuhaoyang** [comment]
@zhaiweihao `serviceCollection.ToServiceContainer()`是`AspectCore.Extensions.DependencyInjection`包中提供的 [ServiceCollectionToContainerExtensions](https://github.com/dotnetcore/AspectCore-Framework/blob/master/extras/src/AspectCore.Extensions.DependencyInjection/ServiceCollectionToContainerExtensions.cs#L12) 这个扩展方法的作用是把在serviceCollection中注册的服务接入到AspectCore内置的IoC中，因为serviceCollection并没有提供属性注入的功能，所以需要借助AspectCore内置的IoC来激活属性注入

**Comment by Basil1991** [comment]
// Startup.cs     
  public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            var container = services.ToServiceContainer();
            container.AddType<ISampleService, SampleService>();
            IServiceResolver sp = container.Build();
            return sp;
        }

        public interface ISampleService {
        }

        public class SampleService : ISampleService {
        }

//ValuesController.cs
  [FromContainer]
        public ISampleService service { get; set; }
        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get() {
            string serviceName = service.ToString();
            return new string[] { serviceName };
        }
 
无法注入.Console我看了也是OK的,WebApi一直不行.

**Comment by zhaiweihao** [comment]
@liuhaoyang 哦哦，开始我没引用`AspectCore.Extensions.DependencyInjection`的nuget包，我是直接new的AspectCore的`ServiceContainer`实例，然后出现不能属性注入。
看来还是要先用dotnetcore自带的`ServiceCollection`创建再转化才成哦

**Comment by liuhaoyang** [comment]
@Basil1991 如果是在Controller中，需要在注册Mvc的时候AddControllersAsServices()
```
  public IServiceProvider ConfigureServices(IServiceCollection services){
        services.AddMvc().AddControllersAsServices();
        var container = services.ToServiceContainer();
        container.AddType<ISampleService, SampleService>();
        IServiceResolver sp = container.Build();
        return sp;
    }
```

**Comment by liuhaoyang** [comment]
@zhaiweihao 由于你没有贴出代码或者其他任何的配置信息，我也不好猜测你出现的问题。直接new的AspectCore的ServiceContainer实例，也是可以实现属性注入的，你可以跑一下下面的代码来验证：
```
    class Program
    {
        static void Main(string[] args)
        {
            var container = new ServiceContainer();
            container.AddType<ILogger, ConsoleLogger>();
            container.AddType<ISampleService, SampleService>();
            var serviceResolver = container.Build();
            var sampleService = serviceResolver.Resolve<ISampleService>();
            sampleService.Invoke();
            Console.ReadKey();
        }
    }

    public interface ILogger
    {
        void Info(string message);
    }

    public class ConsoleLogger : ILogger
    {
        public void Info(string message)
        {
            Console.WriteLine(message);
        }
    }

    public interface ISampleService
    {
        void Invoke();
    }

    public class SampleService : ISampleService
    {
        [FromContainer]
        public ILogger Logger { get; set; }
        
        public void Invoke()
        {
           Logger?.Info("sample service invoke.");
        }
    }
```

**Comment by Basil1991** [comment]
@liuhaoyang 
感谢,加了AddControllersAsServices()在控制器是可以了,

    //Test.cs
    public class Test {
        [FromContainer]
        public ISampleService service { get; set; }

        public string getServiceName() {
            return service.ToString();
        }
    }

   //ValuesController.cs
   new Test().getServiceName();

非控制器情况不行.

**Comment by liuhaoyang** [comment]
@Basil1991 Test的实例是new？ 不是通过IoC创建？

**Comment by zhaiweihao** [comment]
@liuhaoyang 
了解啦，我review了一下我的代码，是我写错啦，，还是对DI了解的不透彻，正在看你们翻译的DI文档~
多谢！

**Comment by Basil1991** [comment]
@liuhaoyang 我试过new 也试过 IoC AddType 都不行.
正常来说new 应该也是可以的吧.

**Comment by liuhaoyang** [comment]
@Basil1991 你可以看我给的sample或者上面贴的代码。对于属性注入你应该有些误解，不管是构造器注入还是属性注入，都是要在IoC环境下才发生的

**Comment by Basil1991** [comment]
@liuhaoyang 原来都是使用构造函数注入的,但是遇到基类构造函数注入后所有子类都需要去实现下基类构造函数,所以打算改成基类属性注入,尝试了aspectcore,还是没法解决.
同样注入,构造函数可以获取到,属性就是为null,是我的思路有问题?
如果思路没问题只是aspectcore使用方式错误的话我可以提供你一个完整的Demo看看.

**Comment by liuhaoyang** [comment]
@Basil1991 提供demo吧

**Comment by Basil1991** [comment]
@liuhaoyang 发现异常是出现在identityserver中,不是一开始说的webapi的原因.
拿identityserver最简单的demo修改了一下https://github.com/Basil1991/aspectcore.IdentityServer.Sample

        //Startup.cs
        public IServiceProvider ConfigureServices(IServiceCollection services) {
            services.AddTransient<ITest, Test>();
            services.AddTransient<IClientStore, ClientService>();
            // configure identity server with in-memory stores, keys, clients and scopes
            services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                .AddInMemoryApiResources(Config.GetApiResources());

            var container = services.ToServiceContainer();
            return container.Build();
        }

    //ClientService.cs
    public class ClientService : IClientStore {
        //一直获取不到
        [FromContainer]
        public ITest _test { get; set; }

        public ClientService(ITest test) {
            //构造函数注入成功
            test.DoSomething();
        }

        public async Task<Client> FindClientByIdAsync(string clientId) {
            //出现异常
            _test.DoSomething();
            return null;
        }
    }

**Comment by liuhaoyang** [comment]
@Basil1991 
![qq 20180124172138](https://user-images.githubusercontent.com/10701915/35324319-5bb05466-012b-11e8-96a0-cffd3ae03513.png)
用你提供的demo断点调试也没有重现问题 ==。无奈╮(╯▽╰)╭

**Comment by Basil1991** [comment]
我这边的_test=null /(ㄒoㄒ)/~~

**Comment by Basil1991** [comment]
@liuhaoyang  非常感谢协助,下次有问题我直接发demo,刚才我这边也可以了(没改过程序,之前一直不行,奇怪).
原来一直失败的非demo程序那边竟然也成功了.
:-(
辛苦了,再次感谢.

**Comment by liuhaoyang** [comment]
@Basil1991 可能是没看程序员老黄历，今天下午不宜写代码呀？
言归正传，如果觉得AspectCore有帮助的话，可以帮忙推荐给其他人呀，^*^~
