### ISSUE TITLE
AspectCore与Castle.Core性能比较

### ISSUE THREAD

**Issue by tangdf** [dotnetcore/AspectCore-Framework#76]
我做一个AspectCore与Castle.Core的测试，分别针对同步方法与异步方法，可是执行的速度相差很大，不知道为什么，是不是使用方式有问题，求解。
我测试的结果如下：

|                      Method |      Mean |     Error |    StdDev |
|---------------------------- |----------:|----------:|----------:|
| Create_By_Castle_Core_Async |  78.28 ns | 1.5851 ns | 1.6278 ns |
|  Create_By_AspectCore_Async | 386.44 ns | 7.7314 ns | 7.2319 ns |
|       Create_By_Castle_Core |  48.40 ns | 0.8871 ns | 0.8298 ns |
|        Create_By_AspectCore | 352.03 ns | 5.2261 ns | 4.8885 ns |

测试代码的地址：
<https://github.com/tangdf/AOPBenchmarkTest>

**Comment by liuhaoyang** [comment]
感谢提出问题，你的性能测试结果还是中肯的，castle空拦截器执行时间50ns，AspectCore空拦截器执行时间300ns左右是我预期中的结果。
从实现机制上来解释下AspectCore和Castle完成的性能差距
1. 如你代码所示，Castle的拦截器注入代理类的时机是在创建代理类的时候，所以它的代理执行耗时只有拦截器实现方法的执行耗时
2. AspectCore的拦截器注入时机发生在调用代理方法的时候，AspectCore在构造代理类的时候会注入切面创建的工厂接口，到真正去执行代理方法的时候，再通过工厂接口根据配置创建拦截器。这样做的好处在于在不改变代理类的情况下，可以动态的配置代理方法所执行的拦截器，以便实现真正的拦截器作用域，测试所看到的执行性能差距便发生在比过程。
以上，我在把拦截器额外耗时控制在纳秒级别之后，故在强大的切面功能和进一步的性能优化之间选择了前者。
