### ISSUE TITLE
IAspectContext  找不到

### ISSUE THREAD

**Issue by chenbigui** [dotnetcore/AspectCore-Framework#84]
IAspectContext  引用哪个包，麻烦说明

**Comment by liuhaoyang** [comment]
你看的文章可能已经过时了。目前版本使用已经重构IAspectContext为 [AspectContext](https://github.com/dotnetcore/AspectCore-Framework/blob/master/core/src/AspectCore.Abstractions/DynamicProxy/AspectContext.cs)  引入AspectCore.Abstractions包，在AspectCore.DynamicProxy 命名空间下面
