### ISSUE TITLE
[Question] 配置IServerCollection 的时候，从IServiceProvider 中获取的服务是否启用属性拦截

### ISSUE THREAD

**Issue by John0King** [dotnetcore/AspectCore-Framework#86]
```C#
services.AddScoped<IAsyncResult>(serverProvider =>
            {
                // 这里这个serviceProvider 是否是Aspect 的provider, 是否拥有属性拦截
                var t = serverProvider.GetRequiredService<CookieOptions>(); 
                
                return Task.FromResult(t);
            });
```

目前我还处于研究阶段，还没怎么用过这个框架， 主要是担心这个问题。

**Comment by liuhaoyang** [comment]
AspectCore 在AspNet Core中提供可选使用MSDI的serviceProvider 和 AspectCore的serviceProvider：
1. 使用MSDI的serviceProvider
```
   public IServiceProvider ConfigureServices(IServiceCollection services)
   {
          services.AddDynamicProxy();
          return services.BuildAspectCoreServiceProvider();
   }
```
2. 使用AspectCore提供的serviceProvider
```
   public IServiceProvider ConfigureServices(IServiceCollection services)
   {
          var container = services.ToServiceContainer();
          return container.Build();
   }
```

**Comment by John0King** [comment]
@liuhaoyang   请问 这两种有什么区别？
因为在微软某处demo 或者  库里面 （忘了具体的哪） 配置服务的时候这样写的
```C#
        public static IServiceCollection AddExt(this IServiceCollection services)
        {
            var provider = services.BuildServiceProvider();
            services.Configure<CookieOptions>(op=>{
                // 这里的类型都是例子
                op.Domain =  provider.GetRequiredService<string>();
            });
            return services;
        }
```

这里的 provider 应该是 微软的 `Microsoft.Extensions.DependencyInjection.ServiceProvider` ,  我担心是这个微软的Provider 没有 拦截效果

**Comment by liuhaoyang** [comment]
[https://github.com/dotnetcore/AspectCore-Framework/blob/master/core/src/AspectCore.Core/Configuration/Extensions/NonAspectsCollectionExtensions.cs](https://github.com/dotnetcore/AspectCore-Framework/blob/master/core/src/AspectCore.Core/Configuration/Extensions/NonAspectsCollectionExtensions.cs) 这里面预置了一些不会被拦截的namespace 。包括System下面的类，Microsoft.开头的类不会被拦截

**Comment by John0King** [comment]
@liuhaoyang   你好像误会我的问题了

我是想问，如果我按上面那个 配置 `CookieOptions` 的方式， 获取一个 **应该拥有拦截**的类，  是否这个类就失去了 拦截效果？

**Comment by liuhaoyang** [comment]
要拦截类的话，应该把方法标记为`virtual` ，如果是属性，也应该把属性标记为`version`，并且拦截器特性标记在`get`或`set`上面，并且不应该使用 ` services.BuildServiceProvider()` 而是使用`services.BuildAspectCoreServiceProvider()`
