### ISSUE TITLE
需要一个AspectContext.UnwrapAsyncReturnValue的镜像方法

### ISSUE THREAD

**Issue by xiaotupansy** [dotnetcore/AspectCore-Framework#91]
如题。
当我需要对返回结果进行操作的时候，如果返回结果是个Task<TResult>，例如Task<IActionResult>之类的，就需要一个封装方法了。

我自己在实现一个缓存接口的时候实现了一个，凑合能用，不知道你们这边有没有更好的实现可以用。
示例代码如下：

var cacheValue = await DistributedCache.GetAsync(cacheKey);
            if (cacheValue != null)
            {
                using (var ms = new MemoryStream(cacheValue))
                {
                    var formatter = new BinaryFormatter();
                    var result = formatter.Deserialize(ms);
                    if (context.IsAsync())
                    {
                        **dynamic member = context.ServiceMethod.ReturnType.GetMember("Result")[0];
                        dynamic temp = System.Convert.ChangeType(result, member.PropertyType);
                        context.ReturnValue = System.Convert.ChangeType(Task.FromResult(temp), context.ServiceMethod.ReturnType);**
                    }
                    else
                    {
                        context.ReturnValue = System.Convert.ChangeType(result, context.ServiceMethod.ReturnType);
                    }
                }
                return;
            }

**Comment by liuhaoyang** [comment]
明白你的意思了，会考虑把内部使用的Unwrap方法以公开的扩展方法提供出来

**Comment by liuhaoyang** [comment]
可以参考https://github.com/dotnetcore/AspectCore-Framework/blob/master/core/src/AspectCore.Core/DynamicProxy/Extensions/AspectContextRuntimeExtensions.cs#L62

**Comment by xiaotupansy** [comment]
收到，感谢！
