### ISSUE TITLE
NonAspectPredicates.AddMethod()方法不起作用

### ISSUE THREAD

**Issue by ByronFeng** [dotnetcore/AspectCore-Framework#95]
![lib](https://user-images.githubusercontent.com/26641643/38348370-f245f748-38d3-11e8-9ee4-6ce5fbfb9e21.png)
上面是我用的引用。

我在Startup.cs中修改了ConfigureServices方法，如下：

 public IServiceProvider ConfigureServices(IServiceCollection services)         {             
                 services.AddMvc().AddControllersAsServices();            
                ContainerBuilder builder = new ContainerBuilder();             
                builder.RegisterDynamicProxy(config => {  
//自定义拦截器                           config.Interceptors.AddTyped<CustomInterceptorAttribute(Predicates.ForNameSpace("aoptest.Services"));
//排除Quer开头的方法
                config.NonAspectPredicates.AddMethod("Quer*");
            });   
          builder.Populate(services); 
                       var dataAccess = Assembly.GetExecutingAssembly();             builder.RegisterAssemblyTypes(dataAccess)                 .Where(t => t.Name.EndsWith("Service"))                 .AsImplementedInterfaces();   
          var container = builder.Build();   
          return new AutofacServiceProvider(container);        
 }

拦截器CustomInterceptorAttribute的定义代码：

public class CustomInterceptorAttribute : AbstractInterceptor
    {
        public override async Task Invoke(AspectContext context, AspectDelegate next)
        {
                await next(context);
                //方法名
                Console.WriteLine("执行方法: "+ context.ImplementationMethod.Name);
        }
    }

要拦截的业务层代码：

 public class UserService : IUserService
    {
        public string AddUser()
        {
            return "AddUser()";
        }

        public string QueryName()
        {
            return "QueryName()";
        }

        public string SayName()
        {
          
            return "SayName()";
        }
    }

在Controller中调用，后台打印如下：

![result](https://user-images.githubusercontent.com/26641643/38348700-e1af6d0e-38d5-11e8-848e-64b08f23bc5a.png)

可以看出
config.NonAspectPredicates.AddMethod("Quer*");并没有起作用。

**Comment by liuhaoyang** [comment]
已修复https://github.com/dotnetcore/AspectCore-Framework/pull/104
